wget http://www.bx.psu.edu/~anton/bioinf-images/4.6.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.7.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.9a.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.9b.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.12.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13a.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13b.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13c.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13d.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13e.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13f.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.15.png
wget http://www.bx.psu.edu/~anton/bioinf-images/koninsberg.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.7.png
wget http://www.bx.psu.edu/~anton/bioinf-images/4.13f.png
wget http://www.bx.psu.edu/~anton/bioinf-images/deBruijn.png
