wget https://github.com/nekrut/galaxy/wiki/images/everything_connected.png
wget https://github.com/nekrut/galaxy/wiki/images/dT_random.png
wget https://github.com/nekrut/galaxy/wiki/images/dna_rna.png
wget https://github.com/nekrut/galaxy/wiki/images/stranded_protocols.png
wget https://github.com/nekrut/galaxy/wiki/images/lib_type.png
wget https://github.com/nekrut/galaxy/wiki/images/stranded_result.png
wget https://github.com/nekrut/galaxy/wiki/images/tophat.png
wget https://github.com/nekrut/galaxy/wiki/images/tophat2.png
wget https://github.com/nekrut/galaxy/wiki/images/hisat.png
wget https://github.com/nekrut/galaxy/wiki/images/star.png
wget https://github.com/nekrut/galaxy/wiki/images/rnaseq_comparison.png
wget https://github.com/nekrut/galaxy/wiki/images/stringtie1.png
wget https://github.com/nekrut/galaxy/wiki/images/sailfish.png
wget https://github.com/nekrut/galaxy/wiki/images/quasi_aln.png
wget https://github.com/nekrut/galaxy/wiki/images/kallisto.png
wget https://github.com/nekrut/galaxy/wiki/images/salmon.png
wget https://github.com/nekrut/galaxy/wiki/images/stringtie2.png
wget https://github.com/nekrut/galaxy/wiki/images/em.png
wget https://github.com/nekrut/galaxy/wiki/images/within_norm.png
wget https://github.com/nekrut/galaxy/wiki/images/diff.png
wget https://github.com/nekrut/galaxy/wiki/images/rnaseq_library.png
wget https://github.com/nekrut/galaxy/wiki/images/rnaseq_data_in_history.png
wget https://github.com/nekrut/galaxy/wiki/images/collections_video.png
wget https://github.com/nekrut/galaxy/wiki/images/tophat_interface.png
wget https://github.com/nekrut/galaxy/wiki/images/tophat_output.png
wget https://github.com/nekrut/galaxy/wiki/images/accepted_hits_1.png
wget https://github.com/nekrut/galaxy/wiki/images/accepted_hits_2.png
wget https://github.com/nekrut/galaxy/wiki/images/igv_tophat.png
wget https://github.com/nekrut/galaxy/wiki/images/sashimi.png
wget https://github.com/nekrut/galaxy/wiki/images/htseq_count.png
wget https://github.com/nekrut/galaxy/wiki/images/ucsc_dm3.png
wget https://github.com/nekrut/galaxy/wiki/images/htseq_count_interface.png
wget https://github.com/nekrut/galaxy/wiki/images/deseq2_interface.png
wget https://github.com/nekrut/galaxy/wiki/images/deseq2_output.png
wget https://github.com/nekrut/galaxy/wiki/images/p_val_hist.png
wget https://github.com/nekrut/galaxy/wiki/images/MA_plot.png
wget https://github.com/nekrut/galaxy/wiki/images/pca.png
wget https://github.com/nekrut/galaxy/wiki/images/euc_dist.png
