wget http://www.pnas.org/content/109/36/14508/F1.expansion.html
wget https://galaxyproject.org/duplex/het.png
wget http://galaxyproject.org/galaxy101/fa-refresh.png
wget http://galaxyproject.org/duplex/histItem.png
wget https://galaxyproject.org/duplex/steps.png
wget https://galaxyproject.org/duplex/abl1-r-qc.png
wget https://galaxyproject.org/duplex/makeCons.png
wget https://galaxyproject.org/duplex/contentTrimmer.png
wget https://galaxyproject.org/duplex/combineFandQ.png
wget https://galaxyproject.org/duplex/multiDataset.png
wget https://galaxyproject.org/duplex/bwa-mem.png
wget https://galaxyproject.org/duplex/bwa.png
wget https://galaxyproject.org/duplex/mergeSamFiles.png
wget https://galaxyproject.org/duplex/leftAlign.png
wget https://galaxyproject.org/duplex/nvc.png
wget https://galaxyproject.org/duplex/va.png
wget https://galaxyproject.org/duplex/filter.png
wget https://galaxyproject.org/duplex/fromReads.png
wget https://galaxyproject.org/duplex/fromDCS.png
